name: ssrcln_app
description: "A professional cleaning service app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.6
  permission_handler: ^10.4.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins

  # ADD THIS SECTION:
  assets:
    - assets/
    - assets/clean1.png
    - assets/clean2.png
    - assets/clean3.png
    - assets/clean4.png
    - assets/offer1.jpg
    - assets/offer2.jpg
    - assets/offer3.jpg
    - assets/offer4.jpg
    - assets/offer5.jpg
    
